tap "homebrew/bundle"
tap "oven-sh/bun"
tap "stripe/stripe-cli"
brew "btop"
brew "difftastic"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "gh"
brew "git"
brew "lazygit"
brew "mas"
brew "mdbtools"
brew "neofetch"
brew "neovim"
brew "nvm"
brew "pkgconf"
brew "python@3.12"
brew "ripgrep"
brew "ruby"
brew "tmux"
brew "uv"
brew "zig"
brew "oven-sh/bun/bun"
brew "stripe/stripe-cli/stripe"
cask "alfred"
cask "alt-tab"
cask "anydesk"
cask "arc"
cask "audacity"
cask "ccleaner"
cask "cloudmounter"
cask "docker-desktop"
cask "ghostty"
cask "google-chrome"
cask "karabiner-elements"
cask "keka"
cask "loopback"
cask "mongodb-compass"
cask "musescore"
cask "ngrok"
cask "obs"
cask "postman"
cask "private-internet-access"
cask "rectangle-pro"
cask "spotify"
cask "stats"
cask "tableplus"
cask "tidal"
cask "tor-browser"
cask "visual-studio-code"
cask "vlc"
mas "Bitwarden", id: 1352778147
mas "CleanMyKeyboard", id: 6468120888
mas "DevCleaner", id: 1388020431
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
