tap "homebrew/bundle"
tap "oven-sh/bun"
tap "stripe/stripe-cli"
brew "btop"
brew "difftastic"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "gh"
brew "git"
brew "lazygit"
brew "mas"
brew "neofetch"
brew "neovim"
brew "nvm"
brew "pkgconf"
brew "ripgrep"
brew "ruby"
brew "tmux"
brew "uv"
brew "zig"
brew "oven-sh/bun/bun"
brew "stripe/stripe-cli/stripe"
cask "anydesk"
cask "ghostty"
cask "ngrok"
cask "rectangle-pro"
cask "screen-studio"
mas "Bitwarden", id: 1352778147
mas "CapCut", id: 1500855883
mas "DevCleaner", id: 1388020431
mas "GarageBand", id: 682658836
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
